/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesAndInventorySystem;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author james
 */
public class AddNewSize extends javax.swing.JFrame {

    /**
     * Creates new form AddNewSize
     */
    public AddNewSize() {
        initComponents();
        showIcon();
    }
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        newSizeTf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        unitSelect = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        sizeInOzTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        jLabel9.setText("oz");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 40));

        newSizeTf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        newSizeTf.setToolTipText("");
        newSizeTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        newSizeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSizeTfActionPerformed(evt);
            }
        });
        newSizeTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newSizeTfKeyReleased(evt);
            }
        });
        jPanel2.add(newSizeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, 40));

        jButton5.setBackground(new java.awt.Color(44, 119, 33));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        jButton5.setText("SAVE");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, 50));

        unitSelect.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        unitSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liter", "Liters" }));
        unitSelect.setFocusable(false);
        unitSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitSelectActionPerformed(evt);
            }
        });
        jPanel2.add(unitSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, 40));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        jLabel10.setText("New Product Size");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 40));

        sizeInOzTf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        sizeInOzTf.setToolTipText("");
        sizeInOzTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        sizeInOzTf.setEnabled(false);
        sizeInOzTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeInOzTfActionPerformed(evt);
            }
        });
        jPanel2.add(sizeInOzTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 130, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        jLabel11.setText("New Product Size");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 40));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
        jLabel12.setText("Size in Ounce");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 450, 240));

        jPanel1.setBackground(new java.awt.Color(0, 224, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ADD NEW SIZE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 230, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        double a = Double.valueOf(newSizeTf.getText());
        String unitt = unitSelect.getSelectedItem().toString();
        
        //if there is a field left blank
        if(newSizeTf.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Please enter data needed!");
        }else if(newSizeTf.getText().matches("^[ A-Za-z]+$")){
            JOptionPane.showMessageDialog(this, "Incorrect Input!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(a > 1 && unitt.equals("Liter")){
            JOptionPane.showMessageDialog(this, "Select Proper Unit!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{

            String newsize = newSizeTf.getText();
            String unit = unitSelect.getSelectedItem().toString();
            String newsize_ = newsize + " " + unit;
            
            DecimalFormat df = new DecimalFormat("#.###");
            double inOz = Double.valueOf(newsize) * 33.814;
            String oz1 = df.format(inOz);
            System.out.println(oz1);
            
            
            try{
                   Statement s = DBConnector.mycon().createStatement();
                   String query = "SELECT * FROM product_size WHERE productsize='"+newsize_+"' ";
                   
                   ResultSet rs1 = s.executeQuery(query);
                   if(!rs1.next()){
            
            try{

                Statement s1 = DBConnector.mycon().createStatement();
                s1.executeUpdate("INSERT INTO product_size (productsize, sizeinounce) "
                    + "VALUES ('"+newsize_+"','"+oz1+"')");

                JOptionPane.showMessageDialog(rootPane, "Added Successfully!");

                newSizeTf.setText("");
                sizeInOzTf.setText("");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }

        }else{
                JOptionPane.showMessageDialog(this, "Size already exists!");
                   }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void unitSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitSelectActionPerformed

    private void newSizeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSizeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSizeTfActionPerformed

    private void sizeInOzTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeInOzTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeInOzTfActionPerformed

    private void newSizeTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSizeTfKeyReleased
            DecimalFormat df = new DecimalFormat("#.###");
            double inOz = Double.valueOf(newSizeTf.getText()) * 33.814;
            String oz1 = df.format(inOz);
            System.out.println(oz1);
            
            sizeInOzTf.setText(oz1);
    }//GEN-LAST:event_newSizeTfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewSize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newSizeTf;
    private javax.swing.JTextField sizeInOzTf;
    private javax.swing.JComboBox<String> unitSelect;
    // End of variables declaration//GEN-END:variables
}
