/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesAndInventorySystem;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author james
 */
public class CustomerMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainMenu
     */
    public static String cnamee;
    public static int userids;
    public static String position;
    public static String username;
    
    public CustomerMainMenu() {
        initComponents();
    }
    
    public CustomerMainMenu(String name, String pos, int userid) {
        
        
        initComponents();
        showDate();
        showTime();
        showUsername.setText(name);
        showPosition.setText(pos);
        
        userids = userid;
        position = pos;
        username = name;
        
        showIcon();
    }
    
    public CustomerMainMenu(String name, String pos, int userid, String cname) {
        
        
        initComponents();
        
        showUsername.setText(name);
        showPosition.setText(pos);
        
        userids = userid;
        position = pos;
        username = name;
        cnamee = cname;
        
        showDate();
        showTime();
        showIcon();
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    public void showDate(){
        System.out.println(cnamee);
        Date d = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String date = sdf.format(d);
        showDate.setText(date);
        
    }
    
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                String time = s.format(d);
                showTime.setText(time);
                
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        showUsername = new javax.swing.JLabel();
        showPosition = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        productMaintenanceBtn10 = new javax.swing.JButton();
        productMaintenanceBtn11 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        productMaintenanceBtn5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        productMaintenanceBtn8 = new javax.swing.JButton();
        productMaintenanceBtn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        productMaintenanceBtn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        salesTransactionMenuBtn = new javax.swing.JMenuItem();
        productInquiryMenuBtn = new javax.swing.JMenuItem();
        returnedProductMenuBtn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        showHelpMenuBtn = new javax.swing.JMenuItem();
        systemDevelopersMenuBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 1830, 0));

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 1, 82)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EL    COCO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 520, 120));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 232, 1810, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sp_3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 170));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar (1).png"))); // NOI18N
        jLabel9.setText("Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 170, 150, 40));

        showDate.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showDate.setText("Date");
        jPanel1.add(showDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 170, 150, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/position.png"))); // NOI18N
        jLabel11.setText("Position:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 70, 130, 50));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jLabel12.setText("Time: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 120, 150, 40));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel13.setText("Current User:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 170, 40));

        showUsername.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showUsername.setText("Name");
        jPanel1.add(showUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 30, 150, 40));

        showPosition.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showPosition.setText("Customer");
        jPanel1.add(showPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 70, 150, 40));

        showTime.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showTime.setText("Time");
        jPanel1.add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 120, 150, 40));

        jButton5.setBackground(new java.awt.Color(44, 119, 33));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 910, 230, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product inquiry_.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 170));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 170));

        productMaintenanceBtn10.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn10.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn10.setText("PURCHASED ORDER");
        productMaintenanceBtn10.setToolTipText("");
        productMaintenanceBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn10.setFocusable(false);
        productMaintenanceBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn10ActionPerformed(evt);
            }
        });
        jPanel12.add(productMaintenanceBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 220, 50));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 220, 170));

        productMaintenanceBtn11.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn11.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn11.setText("PRODUCT INQUIRY");
        productMaintenanceBtn11.setToolTipText("");
        productMaintenanceBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn11.setFocusable(false);
        productMaintenanceBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn11ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 220, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 160));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 450, 220, 170));

        productMaintenanceBtn5.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn5.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn5.setText("HELP");
        productMaintenanceBtn5.setToolTipText("");
        productMaintenanceBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn5.setFocusable(false);
        productMaintenanceBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 620, 220, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return_.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 170));

        productMaintenanceBtn8.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn8.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn8.setText("PURCHASED ORDER");
        productMaintenanceBtn8.setToolTipText("");
        productMaintenanceBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn8.setFocusable(false);
        productMaintenanceBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn8ActionPerformed(evt);
            }
        });
        jPanel10.add(productMaintenanceBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 220, 50));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 220, 170));

        productMaintenanceBtn9.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn9.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn9.setText("RETURN PRODUCT");
        productMaintenanceBtn9.setToolTipText("");
        productMaintenanceBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn9.setFocusable(false);
        productMaintenanceBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, 220, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buy_.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 170));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 220, 170));

        productMaintenanceBtn1.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn1.setText("BUY PRODUCT");
        productMaintenanceBtn1.setToolTipText("");
        productMaintenanceBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn1.setFocusable(false);
        productMaintenanceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 220, 50));

        jButton1.setBackground(new java.awt.Color(44, 119, 33));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jButton1.setText("Minimize");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, -1, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coconut-Tree-PNG-Images__.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -160, 1440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 984));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jMenuBar1.setOpaque(false);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        jMenu3.setText("Transactions");

        salesTransactionMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salesTransactionMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        salesTransactionMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sales transaction.png"))); // NOI18N
        salesTransactionMenuBtn.setText("Sales Transaction");
        salesTransactionMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesTransactionMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(salesTransactionMenuBtn);

        productInquiryMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        productInquiryMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        productInquiryMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product inquiry.png"))); // NOI18N
        productInquiryMenuBtn.setText("Product Inquiry");
        productInquiryMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInquiryMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(productInquiryMenuBtn);

        returnedProductMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        returnedProductMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnedProductMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/returmed product.png"))); // NOI18N
        returnedProductMenuBtn.setText("Return Product");
        jMenu3.add(returnedProductMenuBtn);

        jMenuBar1.add(jMenu3);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jMenu5.setText("Help");

        showHelpMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        showHelpMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        showHelpMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show help.png"))); // NOI18N
        showHelpMenuBtn.setText("Show Help");
        showHelpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHelpMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(showHelpMenuBtn);

        systemDevelopersMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        systemDevelopersMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        systemDevelopersMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system developers.png"))); // NOI18N
        systemDevelopersMenuBtn.setText("System Developers");
        systemDevelopersMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemDevelopersMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(systemDevelopersMenuBtn);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Select option", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged Out";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+userids+"','"+username+"','"+position+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
        }else{
        }
        
        showUsername.setText("");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void salesTransactionMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesTransactionMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesTransactionMenuBtnActionPerformed

    private void productInquiryMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInquiryMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productInquiryMenuBtnActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseClicked

    private void productMaintenanceBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn10ActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void productMaintenanceBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn11ActionPerformed
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn11ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void productMaintenanceBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn5ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       CustomerAddNewReturnedProduct r  = new CustomerAddNewReturnedProduct(cnamee);
        r.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseClicked

    private void productMaintenanceBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn8ActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        CustomerAddNewReturnedProduct r  = new CustomerAddNewReturnedProduct(cnamee);
        r.setVisible(true);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void productMaintenanceBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn9ActionPerformed
        CustomerAddNewReturnedProduct r  = new CustomerAddNewReturnedProduct(cnamee);
        r.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn9ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        CustomerSales s = new CustomerSales(username);
        s.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void productMaintenanceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn1ActionPerformed
        CustomerSales s = new CustomerSales(cnamee);
        s.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        CustomerSales s = new CustomerSales(cnamee);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void systemDevelopersMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemDevelopersMenuBtnActionPerformed
        SystemDevelopers s = new SystemDevelopers();
        s.setVisible(true);
    }//GEN-LAST:event_systemDevelopersMenuBtnActionPerformed

    private void showHelpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHelpMenuBtnActionPerformed
        CustomerHelp c = new CustomerHelp();
        c.setVisible(true);
    }//GEN-LAST:event_showHelpMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem productInquiryMenuBtn;
    private javax.swing.JButton productMaintenanceBtn1;
    private javax.swing.JButton productMaintenanceBtn10;
    private javax.swing.JButton productMaintenanceBtn11;
    private javax.swing.JButton productMaintenanceBtn5;
    private javax.swing.JButton productMaintenanceBtn8;
    private javax.swing.JButton productMaintenanceBtn9;
    private javax.swing.JMenuItem returnedProductMenuBtn;
    private javax.swing.JMenuItem salesTransactionMenuBtn;
    private javax.swing.JLabel showDate;
    private javax.swing.JMenuItem showHelpMenuBtn;
    private javax.swing.JLabel showPosition;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel showUsername;
    private javax.swing.JMenuItem systemDevelopersMenuBtn;
    // End of variables declaration//GEN-END:variables
}
