/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesAndInventorySystem;

import images.ItemCheckerHelp;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static salesAndInventorySystem.MainMenu.position;
import static salesAndInventorySystem.MainMenu.userids;
import static salesAndInventorySystem.MainMenu.username;

/**
 *
 * @author james
 */
public class ItemCheckerMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form ItemCheckerSelect
     */
    public static String username;
    public static int userids;
    public static String position;
    
    public ItemCheckerMainMenu() {
        initComponents();
    }
    
    public ItemCheckerMainMenu(String name, String pos, int userid) {
        
        
        
        initComponents();
        showDate();
        showTime();
        showUsername.setText(name);
        showPosition.setText(pos);
        
        userids = userid;
        position = pos;
        username = name;
        
        showIcon();
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    public void showDate(){
    
        Date d = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String date = sdf.format(d);
        showDate.setText(date);
        
    }
    
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                String time = s.format(d);
                showTime.setText(time);
                
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        showUsername = new javax.swing.JLabel();
        showPosition = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        productsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productMaintenanceBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        productMaintenanceBtn2 = new javax.swing.JButton();
        helpBtn1 = new javax.swing.JPanel();
        helpBtn2 = new javax.swing.JLabel();
        helpBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        productMaintenanceBtn8 = new javax.swing.JButton();
        productMaintenanceBtn9 = new javax.swing.JButton();
        productMaintenanceBtn11 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        productMaintenanceBtn10 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        productMaintenanceBtn12 = new javax.swing.JButton();
        productMaintenanceBtn13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        productMaintenanceMenuBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        productInquiryMenuBtn = new javax.swing.JMenuItem();
        stockAdjustmentMenuBtn = new javax.swing.JMenuItem();
        returnedProductMenuBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        purchasedOrderReportMenuBtn = new javax.swing.JMenuItem();
        inventoryReportMenuBtn = new javax.swing.JMenuItem();
        returnedProductsReportMenuBtn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        showHelpMenuBtn = new javax.swing.JMenuItem();
        systemDevelopersMenuBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 1830, 0));

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 1, 82)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EL    COCO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 520, 120));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 232, 1810, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sp_3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 170));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar (1).png"))); // NOI18N
        jLabel9.setText("Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 170, 150, 40));

        showDate.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showDate.setText("Date");
        jPanel1.add(showDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 170, 150, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/position.png"))); // NOI18N
        jLabel11.setText("Position:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 70, 130, 50));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jLabel12.setText("Time: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 120, 150, 40));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel13.setText("Current User:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 170, 40));

        showUsername.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showUsername.setText("Name");
        jPanel1.add(showUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 30, 150, 40));

        showPosition.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showPosition.setText("Position");
        jPanel1.add(showPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 70, 150, 40));

        showTime.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showTime.setText("Time");
        jPanel1.add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 120, 150, 40));

        jButton5.setBackground(new java.awt.Color(44, 119, 33));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 910, 230, 50));

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));
        productsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        productsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsPanelMouseClicked(evt);
            }
        });
        productsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products__.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        productsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 180));

        jPanel1.add(productsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 220, 170));

        productMaintenanceBtn.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn.setText("PRODUCTS");
        productMaintenanceBtn.setToolTipText("");
        productMaintenanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn.setFocusable(false);
        productMaintenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 220, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 160));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, 220, 170));

        productMaintenanceBtn2.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn2.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn2.setText("STOCKS");
        productMaintenanceBtn2.setToolTipText("");
        productMaintenanceBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn2.setFocusable(false);
        productMaintenanceBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 220, 50));

        helpBtn1.setBackground(new java.awt.Color(255, 255, 255));
        helpBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        helpBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBtn1MouseClicked(evt);
            }
        });
        helpBtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_.png"))); // NOI18N
        helpBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBtn2MouseClicked(evt);
            }
        });
        helpBtn1.add(helpBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 160));

        jPanel1.add(helpBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 440, 220, 170));

        helpBtn.setBackground(new java.awt.Color(44, 119, 33));
        helpBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        helpBtn.setForeground(new java.awt.Color(255, 255, 255));
        helpBtn.setText("HELP");
        helpBtn.setToolTipText("");
        helpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpBtn.setFocusable(false);
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(helpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 610, 220, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return_.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 170));

        productMaintenanceBtn8.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn8.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn8.setText("PURCHASED ORDER");
        productMaintenanceBtn8.setToolTipText("");
        productMaintenanceBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn8.setFocusable(false);
        productMaintenanceBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn8ActionPerformed(evt);
            }
        });
        jPanel10.add(productMaintenanceBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 220, 50));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 220, 170));

        productMaintenanceBtn9.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn9.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn9.setText("RETURNED PRODUCT");
        productMaintenanceBtn9.setToolTipText("");
        productMaintenanceBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn9.setFocusable(false);
        productMaintenanceBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 220, 50));

        productMaintenanceBtn11.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn11.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn11.setText("PRODUCT INQUIRY");
        productMaintenanceBtn11.setToolTipText("");
        productMaintenanceBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn11.setFocusable(false);
        productMaintenanceBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn11ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 220, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product inquiry_.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 170));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 170));

        productMaintenanceBtn10.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn10.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn10.setText("PURCHASED ORDER");
        productMaintenanceBtn10.setToolTipText("");
        productMaintenanceBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn10.setFocusable(false);
        productMaintenanceBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn10ActionPerformed(evt);
            }
        });
        jPanel12.add(productMaintenanceBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 220, 50));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 220, 170));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory report_.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, 170));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 220, 170));

        productMaintenanceBtn12.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn12.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn12.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn12.setText("PURCHASED ORDER");
        productMaintenanceBtn12.setToolTipText("");
        productMaintenanceBtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn12.setFocusable(false);
        productMaintenanceBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn12ActionPerformed(evt);
            }
        });
        jPanel14.add(productMaintenanceBtn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 220, 50));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 440, 220, 170));

        productMaintenanceBtn13.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn13.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn13.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn13.setText("INVENTORY REPORT");
        productMaintenanceBtn13.setToolTipText("");
        productMaintenanceBtn13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn13.setFocusable(false);
        productMaintenanceBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn13ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 610, 220, 50));

        jButton1.setBackground(new java.awt.Color(44, 119, 33));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jButton1.setText("Minimize");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, -1, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coconut-Tree-PNG-Images__.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -160, 1440, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jMenuBar1.setOpaque(false);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maintenance.png"))); // NOI18N
        jMenu2.setText("Maintenance");

        productMaintenanceMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        productMaintenanceMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        productMaintenanceMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product maintenance.png"))); // NOI18N
        productMaintenanceMenuBtn.setText("Product Maintenance");
        productMaintenanceMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(productMaintenanceMenuBtn);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        jMenu3.setText("Transactions");

        productInquiryMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        productInquiryMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        productInquiryMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product inquiry.png"))); // NOI18N
        productInquiryMenuBtn.setText("Product Inquiry");
        productInquiryMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInquiryMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(productInquiryMenuBtn);

        stockAdjustmentMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        stockAdjustmentMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        stockAdjustmentMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock adjustment.png"))); // NOI18N
        stockAdjustmentMenuBtn.setText("Stock Adjustment");
        jMenu3.add(stockAdjustmentMenuBtn);

        returnedProductMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        returnedProductMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnedProductMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/returmed product.png"))); // NOI18N
        returnedProductMenuBtn.setText("Returned Product");
        jMenu3.add(returnedProductMenuBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reports.png"))); // NOI18N
        jMenu4.setText("Reports");

        purchasedOrderReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        purchasedOrderReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchsed order.png"))); // NOI18N
        purchasedOrderReportMenuBtn.setText("Purchased Order Reports");
        jMenu4.add(purchasedOrderReportMenuBtn);

        inventoryReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventoryReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory report.png"))); // NOI18N
        inventoryReportMenuBtn.setText("Inventory Report");
        jMenu4.add(inventoryReportMenuBtn);

        returnedProductsReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnedProductsReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/returmed product.png"))); // NOI18N
        returnedProductsReportMenuBtn.setText("Returned Products Report");
        jMenu4.add(returnedProductsReportMenuBtn);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jMenu5.setText("Help");

        showHelpMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        showHelpMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        showHelpMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show help.png"))); // NOI18N
        showHelpMenuBtn.setText("Show Help");
        showHelpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHelpMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(showHelpMenuBtn);

        systemDevelopersMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        systemDevelopersMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        systemDevelopersMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system developers.png"))); // NOI18N
        systemDevelopersMenuBtn.setText("System Developers");
        systemDevelopersMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemDevelopersMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(systemDevelopersMenuBtn);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Select option", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged Out";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+userids+"','"+username+"','"+position+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
        }else{
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void productMaintenanceMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceMenuBtnActionPerformed
        ProductMaintenance p = new ProductMaintenance();
    }//GEN-LAST:event_productMaintenanceMenuBtnActionPerformed

    private void productInquiryMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInquiryMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productInquiryMenuBtnActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ProductMaintenance p = new ProductMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void productsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsPanelMouseClicked
        ProductMaintenance p = new ProductMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_productsPanelMouseClicked

    private void productMaintenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtnActionPerformed
        ProductMaintenance a = new ProductMaintenance();
        a.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void productMaintenanceBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn2ActionPerformed
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn2ActionPerformed

    private void helpBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpBtn2MouseClicked
        ItemCheckerHelp i = new ItemCheckerHelp();
        i.setVisible(true);
    }//GEN-LAST:event_helpBtn2MouseClicked

    private void helpBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpBtn1MouseClicked
        ItemCheckerHelp i = new ItemCheckerHelp();
        i.setVisible(true);
    }//GEN-LAST:event_helpBtn1MouseClicked

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        ItemCheckerHelp i = new ItemCheckerHelp();
        i.setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        ReturnedProducts r  = new ReturnedProducts();
        r.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseClicked

    private void productMaintenanceBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn8ActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        ReturnedProducts r  = new ReturnedProducts();
        r.setVisible(true);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void productMaintenanceBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn9ActionPerformed
       ReturnedProducts r  = new ReturnedProducts();
        r.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn9ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseClicked

    private void productMaintenanceBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn10ActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void productMaintenanceBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn11ActionPerformed
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn11ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        InventoryReport i = new InventoryReport();
        i.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseClicked

    private void productMaintenanceBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productMaintenanceBtn12ActionPerformed

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        InventoryReport i = new InventoryReport();
        i.setVisible(true);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void productMaintenanceBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn13ActionPerformed
        InventoryReport i = new InventoryReport();
        i.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void systemDevelopersMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemDevelopersMenuBtnActionPerformed
        SystemDevelopers s = new SystemDevelopers();
        s.setVisible(true);
    }//GEN-LAST:event_systemDevelopersMenuBtnActionPerformed

    private void showHelpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHelpMenuBtnActionPerformed
        ItemCheckerHelp i = new ItemCheckerHelp();
        i.setVisible(true);
    }//GEN-LAST:event_showHelpMenuBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        About a = new About();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCheckerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCheckerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCheckerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCheckerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCheckerMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpBtn;
    private javax.swing.JPanel helpBtn1;
    private javax.swing.JLabel helpBtn2;
    private javax.swing.JMenuItem inventoryReportMenuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem productInquiryMenuBtn;
    private javax.swing.JButton productMaintenanceBtn;
    private javax.swing.JButton productMaintenanceBtn10;
    private javax.swing.JButton productMaintenanceBtn11;
    private javax.swing.JButton productMaintenanceBtn12;
    private javax.swing.JButton productMaintenanceBtn13;
    private javax.swing.JButton productMaintenanceBtn2;
    private javax.swing.JButton productMaintenanceBtn8;
    private javax.swing.JButton productMaintenanceBtn9;
    private javax.swing.JMenuItem productMaintenanceMenuBtn;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JMenuItem purchasedOrderReportMenuBtn;
    private javax.swing.JMenuItem returnedProductMenuBtn;
    private javax.swing.JMenuItem returnedProductsReportMenuBtn;
    private javax.swing.JLabel showDate;
    private javax.swing.JMenuItem showHelpMenuBtn;
    private javax.swing.JLabel showPosition;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel showUsername;
    private javax.swing.JMenuItem stockAdjustmentMenuBtn;
    private javax.swing.JMenuItem systemDevelopersMenuBtn;
    // End of variables declaration//GEN-END:variables
}
