/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesAndInventorySystem;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static salesAndInventorySystem.CustomerSales.customerid;

/**
 *
 * @author james
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public static String firstnamee;
    public static String lastnamee;
    
    public Login() {
        initComponents();
        showIcon();
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        showPass = new javax.swing.JCheckBox();
        exitBtn = new javax.swing.JButton();
        customerLogin = new javax.swing.JButton();
        passwordTf = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 224, 145));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png"))); // NOI18N
        jPanel3.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 470));

        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 1, 48)); // NOI18N
        jLabel1.setText("EL COCO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 29, -1, -1));

        usernameTf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        usernameTf.setForeground(new java.awt.Color(204, 204, 204));
        usernameTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTf.setText("Enter Username");
        usernameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        usernameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTfFocusLost(evt);
            }
        });
        usernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTfActionPerformed(evt);
            }
        });
        jPanel2.add(usernameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, 50));

        showPass.setBackground(new java.awt.Color(255, 255, 255));
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel2.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 30));

        exitBtn.setBackground(new java.awt.Color(44, 119, 33));
        exitBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setFocusPainted(false);
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 310, 50));

        customerLogin.setBackground(new java.awt.Color(44, 119, 33));
        customerLogin.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        customerLogin.setForeground(new java.awt.Color(255, 255, 255));
        customerLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        customerLogin.setText("NEW CUSTOMER");
        customerLogin.setBorder(null);
        customerLogin.setBorderPainted(false);
        customerLogin.setFocusable(false);
        customerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLoginActionPerformed(evt);
            }
        });
        jPanel2.add(customerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 310, 50));

        passwordTf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        passwordTf.setForeground(new java.awt.Color(204, 204, 204));
        passwordTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTf.setText("Password");
        passwordTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        passwordTf.setMargin(new java.awt.Insets(2, 2, 2, 20));
        passwordTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTfFocusLost(evt);
            }
        });
        jPanel2.add(passwordTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 310, 50));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 13)); // NOI18N
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 13)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        loginBtn.setBackground(new java.awt.Color(44, 119, 33));
        loginBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.png"))); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(null);
        loginBtn.setBorderPainted(false);
        loginBtn.setFocusable(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 310, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
            if(showPass.isSelected()){
                passwordTf.setEchoChar((char)0);
            }else{
                passwordTf.setEchoChar('\u25CF');
            }
    }//GEN-LAST:event_showPassActionPerformed

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void usernameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusGained
        if(usernameTf.getText().equals("Enter Username")){
            usernameTf.setText("");
            usernameTf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_usernameTfFocusGained

    private void usernameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusLost
        if(usernameTf.getText().equals("")){
            usernameTf.setText("Enter Username");
            usernameTf.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_usernameTfFocusLost

    private void passwordTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusLost
        if(passwordTf.getText().equals("")){
            passwordTf.setText("Password");
            passwordTf.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_passwordTfFocusLost

    private void passwordTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusGained
        if(passwordTf.getText().equals("Password")){
            passwordTf.setText("");
            passwordTf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passwordTfFocusGained

    private void customerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLoginActionPerformed
        AddNewCustomer a = new AddNewCustomer();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerLoginActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameTf.getText();
            String password = passwordTf.getText();
            
            try{
                con = DBConnector.mycon();
                pst = con.prepareStatement("select * from user_maintenance where username=? and password=?");
                pst.setString(1, username);
                pst.setString(2, password);
                rs = pst.executeQuery();
                
                if(rs.next()){
                        String id = rs.getString("user_id");
                        int userid = Integer.valueOf(id);
                        String pos = rs.getString("position");
                        System.out.println(pos);
                        if(pos.equals("Item Checker")){
                            ItemCheckerMainMenu m = new ItemCheckerMainMenu(username, pos, userid);
                            m.setVisible(true);
                            this.setVisible(false);
                            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged In";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+id+"','"+username+"','"+pos+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
                            
                        }
                        if(pos.equals("Admin")){
                            MainMenu m = new MainMenu(username, pos, userid);
                            m.setVisible(true);
                            this.setVisible(false);
                            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged In";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+id+"','"+username+"','"+pos+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
                        }
                        if(pos.equals("Cashier")){
                            CashierMainMenu m = new CashierMainMenu(username, pos, userid);
                            m.setVisible(true);
                            this.setVisible(false);
                            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged In";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+id+"','"+username+"','"+pos+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
                        }
                        if(pos.equals("Customer")){
                            //get name of customer
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            ResultSet rs1 = s.executeQuery("SELECT user_id, firstname, lastname FROM user_maintenance WHERE user_id ='"+id+"' ");
                            
                                if(rs1.next()){
                                    firstnamee = (rs1.getString("firstname"));
                                    lastnamee = (rs1.getString("lastname"));
                                }
                                
                                System.out.println(firstnamee + lastnamee);
                                System.out.println(id);
            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
                            
                            String name = firstnamee + " " + lastnamee;
                            
                            CustomerMainMenu m = new CustomerMainMenu(username, pos, userid, name);
                            m.setVisible(true);
                            this.setVisible(false);
                            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged In";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+id+"','"+username+"','"+pos+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
                        }
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Username and Password not matched!", "Error", 1);
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerLogin;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
