/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesAndInventorySystem;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static salesAndInventorySystem.SalesTransaction.customerid;

/**
 *
 * @author james
 */
public final class MainMenu extends javax.swing.JFrame{

    /**
     * Creates new form MainMenu
     */
    public static String username;
    public static int userids;
    public static String position;
    
    public MainMenu() {
        initComponents();
        
        showIcon();
        
    }
    
    public MainMenu(String name, String pos, int userid) {
        
        
        
        initComponents();
        showDate();
        showTime();
        showIcon();
        
        showUsername.setText(name);
        showPosition.setText(pos);
        
        userids = userid;
        position = pos;
        username = name;
        
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    public void showDate(){
    
        Date d = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String date = sdf.format(d);
        showDate.setText(date);
        
    }
    
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                String time = s.format(d);
                showTime.setText(time);
                
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        productMaintenanceBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        showUsername = new javax.swing.JLabel();
        showPosition = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        productsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productMaintenanceBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        productMaintenanceBtn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        productMaintenanceBtn3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        productMaintenanceBtn4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        productMaintenanceBtn5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        productMaintenanceBtn6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        productMaintenanceMenuBtn = new javax.swing.JMenuItem();
        supplierMaintenanceMenuBtn = new javax.swing.JMenuItem();
        customerMaintenanceMenuBtn = new javax.swing.JMenuItem();
        userMaintenanceMenuBtn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salesTransactionMenuBtn = new javax.swing.JMenuItem();
        purchasedOrderMenuBtn = new javax.swing.JMenuItem();
        productInquiryMenuBtn = new javax.swing.JMenuItem();
        stockAdjustmentMenuBtn = new javax.swing.JMenuItem();
        returnedProductMenuBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        salesReportMenuBtn = new javax.swing.JMenuItem();
        purchasedOrderReportMenuBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        inventoryReportMenuBtn = new javax.swing.JMenuItem();
        returnedProductsReportMenuBtn = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        auditTrailReportMenuBtn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        showHelpMenuBtn = new javax.swing.JMenuItem();
        systemDevelopersMenuBtn = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Coco Sales and Inventory System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productMaintenanceBtn.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn.setText("PRODUCTS");
        productMaintenanceBtn.setToolTipText("");
        productMaintenanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn.setFocusable(false);
        productMaintenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 220, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 1830, 0));

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 1, 82)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EL    COCO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 520, 120));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 232, 1810, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sp_3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 170));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar (1).png"))); // NOI18N
        jLabel9.setText("Date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 170, 150, 40));

        showDate.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showDate.setText("Date");
        jPanel1.add(showDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 170, 150, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/position.png"))); // NOI18N
        jLabel11.setText("Position:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 70, 130, 50));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jLabel12.setText("Time: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 120, 150, 40));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel13.setText("Current User:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 170, 40));

        showUsername.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showUsername.setText("Name");
        jPanel1.add(showUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 30, 150, 40));

        showPosition.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showPosition.setText("Position");
        jPanel1.add(showPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 70, 150, 40));

        showTime.setFont(new java.awt.Font("Franklin Gothic Book", 1, 22)); // NOI18N
        showTime.setText("Time");
        jPanel1.add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 120, 150, 40));

        jButton5.setBackground(new java.awt.Color(44, 119, 33));
        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 910, 230, 50));

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));
        productsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        productsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsPanelMouseClicked(evt);
            }
        });
        productsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products__.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        productsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 180));

        jPanel1.add(productsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 220, 170));

        productMaintenanceBtn1.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn1.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn1.setText("SALES");
        productMaintenanceBtn1.setToolTipText("");
        productMaintenanceBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn1.setFocusable(false);
        productMaintenanceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 220, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sales__.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 170));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 220, 170));

        productMaintenanceBtn2.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn2.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn2.setText("STOCKS");
        productMaintenanceBtn2.setToolTipText("");
        productMaintenanceBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn2.setFocusable(false);
        productMaintenanceBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 220, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 160));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 220, 170));

        productMaintenanceBtn3.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn3.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn3.setText("SALES REPORTS");
        productMaintenanceBtn3.setToolTipText("");
        productMaintenanceBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn3.setFocusable(false);
        productMaintenanceBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 460, 220, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salesreports_.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 290, 220, 170));

        productMaintenanceBtn4.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        productMaintenanceBtn4.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn4.setText("PURCHASED ORDER");
        productMaintenanceBtn4.setToolTipText("");
        productMaintenanceBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn4.setFocusable(false);
        productMaintenanceBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 770, 220, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasedorder_.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 170));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 220, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 160));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 600, 220, 170));

        productMaintenanceBtn5.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn5.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn5.setText("HELP");
        productMaintenanceBtn5.setToolTipText("");
        productMaintenanceBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn5.setFocusable(false);
        productMaintenanceBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 770, 220, 50));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users__.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 170));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 220, 170));

        productMaintenanceBtn6.setBackground(new java.awt.Color(44, 119, 33));
        productMaintenanceBtn6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        productMaintenanceBtn6.setForeground(new java.awt.Color(255, 255, 255));
        productMaintenanceBtn6.setText("ACCOUNTS");
        productMaintenanceBtn6.setToolTipText("");
        productMaintenanceBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMaintenanceBtn6.setFocusable(false);
        productMaintenanceBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(productMaintenanceBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 770, 220, 50));

        jButton1.setBackground(new java.awt.Color(44, 119, 33));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jButton1.setText("Minimize");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, -1, 40));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 480, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coconut-Tree-PNG-Images__.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -160, 1440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 984));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 119, 33)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jMenuBar1.setOpaque(false);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maintenance.png"))); // NOI18N
        jMenu2.setText("Maintenance");

        productMaintenanceMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        productMaintenanceMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        productMaintenanceMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product maintenance.png"))); // NOI18N
        productMaintenanceMenuBtn.setText("Product Maintenance");
        productMaintenanceMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMaintenanceMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(productMaintenanceMenuBtn);

        supplierMaintenanceMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        supplierMaintenanceMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        supplierMaintenanceMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/supplier maintenance.png"))); // NOI18N
        supplierMaintenanceMenuBtn.setText("Supplier Maintenance");
        supplierMaintenanceMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMaintenanceMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(supplierMaintenanceMenuBtn);

        customerMaintenanceMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        customerMaintenanceMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        customerMaintenanceMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer maintenance.png"))); // NOI18N
        customerMaintenanceMenuBtn.setText("Customer Maintenance");
        customerMaintenanceMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMaintenanceMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(customerMaintenanceMenuBtn);

        userMaintenanceMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        userMaintenanceMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        userMaintenanceMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usermain.png"))); // NOI18N
        userMaintenanceMenuBtn.setText("User Maintenance");
        userMaintenanceMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMaintenanceMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(userMaintenanceMenuBtn);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction maintenance.png"))); // NOI18N
        jMenuItem2.setText("Sales Maintenance");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchased order maintenance.png"))); // NOI18N
        jMenuItem4.setText("Purchased Orders Maintenance");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        jMenu3.setText("Transactions");

        salesTransactionMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salesTransactionMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        salesTransactionMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sales transaction.png"))); // NOI18N
        salesTransactionMenuBtn.setText("Sales Transaction");
        salesTransactionMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesTransactionMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(salesTransactionMenuBtn);

        purchasedOrderMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        purchasedOrderMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        purchasedOrderMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchsed order.png"))); // NOI18N
        purchasedOrderMenuBtn.setText("Purchased Order");
        purchasedOrderMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasedOrderMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(purchasedOrderMenuBtn);

        productInquiryMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        productInquiryMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        productInquiryMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product inquiry.png"))); // NOI18N
        productInquiryMenuBtn.setText("Product Inquiry");
        productInquiryMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInquiryMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(productInquiryMenuBtn);

        stockAdjustmentMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        stockAdjustmentMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        stockAdjustmentMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock adjustment.png"))); // NOI18N
        stockAdjustmentMenuBtn.setText("Stock Adjustment");
        stockAdjustmentMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAdjustmentMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(stockAdjustmentMenuBtn);

        returnedProductMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        returnedProductMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnedProductMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/returmed product.png"))); // NOI18N
        returnedProductMenuBtn.setText("Returned Product");
        returnedProductMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedProductMenuBtnActionPerformed(evt);
            }
        });
        jMenu3.add(returnedProductMenuBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reports.png"))); // NOI18N
        jMenu4.setText("Reports");

        salesReportMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        salesReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        salesReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sales report.png"))); // NOI18N
        salesReportMenuBtn.setText("Sales Reports");
        salesReportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportMenuBtnActionPerformed(evt);
            }
        });
        jMenu4.add(salesReportMenuBtn);

        purchasedOrderReportMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        purchasedOrderReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        purchasedOrderReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchsed order.png"))); // NOI18N
        purchasedOrderReportMenuBtn.setText("Purchased Order Reports");
        purchasedOrderReportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasedOrderReportMenuBtnActionPerformed(evt);
            }
        });
        jMenu4.add(purchasedOrderReportMenuBtn);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product maintenance.png"))); // NOI18N
        jMenuItem1.setText("Purchased Order Transactions");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        inventoryReportMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        inventoryReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventoryReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory report.png"))); // NOI18N
        inventoryReportMenuBtn.setText("Inventory Report");
        inventoryReportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryReportMenuBtnActionPerformed(evt);
            }
        });
        jMenu4.add(inventoryReportMenuBtn);

        returnedProductsReportMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        returnedProductsReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnedProductsReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/returmed product.png"))); // NOI18N
        returnedProductsReportMenuBtn.setText("Returned Products Report");
        returnedProductsReportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedProductsReportMenuBtnActionPerformed(evt);
            }
        });
        jMenu4.add(returnedProductsReportMenuBtn);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/supplier maintenance.png"))); // NOI18N
        jMenuItem5.setText("Suppliers Report");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        auditTrailReportMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        auditTrailReportMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        auditTrailReportMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/audit trail.png"))); // NOI18N
        auditTrailReportMenuBtn.setText("Audit Trail Report");
        auditTrailReportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditTrailReportMenuBtnActionPerformed(evt);
            }
        });
        jMenu4.add(auditTrailReportMenuBtn);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jMenu5.setText("Help");

        showHelpMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        showHelpMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        showHelpMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show help.png"))); // NOI18N
        showHelpMenuBtn.setText("Show Help");
        showHelpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHelpMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(showHelpMenuBtn);

        systemDevelopersMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        systemDevelopersMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        systemDevelopersMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system developers.png"))); // NOI18N
        systemDevelopersMenuBtn.setText("System Developers");
        systemDevelopersMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemDevelopersMenuBtnActionPerformed(evt);
            }
        });
        jMenu5.add(systemDevelopersMenuBtn);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void productMaintenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtnActionPerformed
        ProductMaintenance a = new ProductMaintenance();
        a.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtnActionPerformed

    private void productMaintenanceMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceMenuBtnActionPerformed
        ProductMaintenance p = new ProductMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_productMaintenanceMenuBtnActionPerformed

    private void salesTransactionMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesTransactionMenuBtnActionPerformed
        SalesTransaction s = new SalesTransaction();
        s.setVisible(true);
    }//GEN-LAST:event_salesTransactionMenuBtnActionPerformed

    private void productInquiryMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInquiryMenuBtnActionPerformed
        ProductInquiry p = new ProductInquiry();
        p.setVisible(true);
    }//GEN-LAST:event_productInquiryMenuBtnActionPerformed

    private void auditTrailReportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditTrailReportMenuBtnActionPerformed
        AuditTrailReport a = new AuditTrailReport();
        a.setVisible(true);
    }//GEN-LAST:event_auditTrailReportMenuBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Select option", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
            
                            java.util.Date d = new java.util.Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String date = sdf.format(d);
                            
                            SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss a");
                            String time = sdft.format(d);
                            String status = "Logged Out";
                            
                            try{
                            Statement s = DBConnector.mycon().createStatement();
                            s.executeUpdate("INSERT INTO audit_trail (`user_id`, `username`, `position`,`time`, `date`, `status`) "
                                            + "VALUES ('"+userids+"','"+username+"','"+position+"','"+time+"','"+date+"','"+status+"')");
                            
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(this, e);
                            }
        }else{
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void supplierMaintenanceMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMaintenanceMenuBtnActionPerformed
        SupplierMaintenance s = new SupplierMaintenance();
        s.setVisible(true);
    }//GEN-LAST:event_supplierMaintenanceMenuBtnActionPerformed

    private void customerMaintenanceMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMaintenanceMenuBtnActionPerformed
        CustomerMaintenance s = new CustomerMaintenance();
        s.setVisible(true);
    }//GEN-LAST:event_customerMaintenanceMenuBtnActionPerformed

    private void userMaintenanceMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMaintenanceMenuBtnActionPerformed
        UserMaintenance s = new UserMaintenance();
        s.setVisible(true);
    }//GEN-LAST:event_userMaintenanceMenuBtnActionPerformed

    private void purchasedOrderMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasedOrderMenuBtnActionPerformed
        PurchasedOrder p = new PurchasedOrder();
        p.setVisible(true);
    }//GEN-LAST:event_purchasedOrderMenuBtnActionPerformed

    private void productMaintenanceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn1ActionPerformed
        SalesTransaction s = new SalesTransaction();
        s.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn1ActionPerformed

    private void productMaintenanceBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn2ActionPerformed
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn2ActionPerformed

    private void productMaintenanceBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn3ActionPerformed
        SalesReport s = new SalesReport();
        s.setVisible(true);
        
    }//GEN-LAST:event_productMaintenanceBtn3ActionPerformed

    private void productMaintenanceBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn4ActionPerformed
        PurchasedOrder p = new PurchasedOrder();
        p.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn4ActionPerformed

    private void productMaintenanceBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn5ActionPerformed
        ShowHelp s = new ShowHelp();
        s.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn5ActionPerformed

    private void productMaintenanceBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMaintenanceBtn6ActionPerformed
        UserMaintenance u = new UserMaintenance();
        u.setVisible(true);
    }//GEN-LAST:event_productMaintenanceBtn6ActionPerformed

    private void productsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsPanelMouseClicked
        ProductMaintenance p = new ProductMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_productsPanelMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ProductMaintenance p = new ProductMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        SalesTransaction s = new SalesTransaction();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        SalesTransaction s = new SalesTransaction();
        s.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        SalesReport s = new SalesReport();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        SalesReport s = new SalesReport();
        s.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        PurchasedOrder p = new PurchasedOrder();
        p.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        PurchasedOrder p = new PurchasedOrder();
        p.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        UserMaintenance u = new UserMaintenance();
        u.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        UserMaintenance u = new UserMaintenance();
        u.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        ShowHelp s = new ShowHelp();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        ShowHelp s = new ShowHelp();
        s.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void stockAdjustmentMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockAdjustmentMenuBtnActionPerformed
        StockAdjustment s = new StockAdjustment();
        s.setVisible(true);
    }//GEN-LAST:event_stockAdjustmentMenuBtnActionPerformed

    private void returnedProductMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedProductMenuBtnActionPerformed
        ReturnedProducts a = new ReturnedProducts();
        a.setVisible(true);
    }//GEN-LAST:event_returnedProductMenuBtnActionPerformed

    private void salesReportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportMenuBtnActionPerformed
        SalesReport s = new SalesReport();
        s.setVisible(true);
    }//GEN-LAST:event_salesReportMenuBtnActionPerformed

    private void purchasedOrderReportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasedOrderReportMenuBtnActionPerformed
        PuchasedOrderReport_2 p = new PuchasedOrderReport_2();
        p.setVisible(true);
    }//GEN-LAST:event_purchasedOrderReportMenuBtnActionPerformed

    private void inventoryReportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryReportMenuBtnActionPerformed
        InventoryReport i = new InventoryReport();
        i.setVisible(true);
    }//GEN-LAST:event_inventoryReportMenuBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PurchasedOrderTransactions p = new PurchasedOrderTransactions();
        p.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void returnedProductsReportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedProductsReportMenuBtnActionPerformed
        ReturnProductsReport r = new ReturnProductsReport();
        r.setVisible(true);
    }//GEN-LAST:event_returnedProductsReportMenuBtnActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PurchasedOrderMaintenance p = new PurchasedOrderMaintenance();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SalesMaintenance s = new SalesMaintenance();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void systemDevelopersMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemDevelopersMenuBtnActionPerformed
        SystemDevelopers s = new SystemDevelopers();
        s.setVisible(true);
    }//GEN-LAST:event_systemDevelopersMenuBtnActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SupplierReport s = new SupplierReport();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void showHelpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHelpMenuBtnActionPerformed
        ShowHelp s = new ShowHelp();
        s.setVisible(true);
    }//GEN-LAST:event_showHelpMenuBtnActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        About a = new About();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem auditTrailReportMenuBtn;
    private javax.swing.JMenuItem customerMaintenanceMenuBtn;
    private javax.swing.JMenuItem inventoryReportMenuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem productInquiryMenuBtn;
    private javax.swing.JButton productMaintenanceBtn;
    private javax.swing.JButton productMaintenanceBtn1;
    private javax.swing.JButton productMaintenanceBtn2;
    private javax.swing.JButton productMaintenanceBtn3;
    private javax.swing.JButton productMaintenanceBtn4;
    private javax.swing.JButton productMaintenanceBtn5;
    private javax.swing.JButton productMaintenanceBtn6;
    private javax.swing.JMenuItem productMaintenanceMenuBtn;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JMenuItem purchasedOrderMenuBtn;
    private javax.swing.JMenuItem purchasedOrderReportMenuBtn;
    private javax.swing.JMenuItem returnedProductMenuBtn;
    private javax.swing.JMenuItem returnedProductsReportMenuBtn;
    private javax.swing.JMenuItem salesReportMenuBtn;
    private javax.swing.JMenuItem salesTransactionMenuBtn;
    private javax.swing.JLabel showDate;
    private javax.swing.JMenuItem showHelpMenuBtn;
    private javax.swing.JLabel showPosition;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel showUsername;
    private javax.swing.JMenuItem stockAdjustmentMenuBtn;
    private javax.swing.JMenuItem supplierMaintenanceMenuBtn;
    private javax.swing.JMenuItem systemDevelopersMenuBtn;
    private javax.swing.JMenuItem userMaintenanceMenuBtn;
    // End of variables declaration//GEN-END:variables
}
