package salesAndInventorySystem;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ee
 */
public class PuchasedOrderReport_2 extends javax.swing.JFrame {

    /**
     * Creates new form PuchasedOrderReport
     */
    public static String supplierid;
    
    public PuchasedOrderReport_2() {
        initComponents();
        setRecordsToTable();
        suppSelect();
        showIcon();
    }
    
    public void suppSelect(){
        
        try{
            Statement s = DBConnector.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM supplier_maintenance");
            Vector v = new Vector();
            
            while(rs.next()){
                v.add(rs.getString("suppliername"));
                
                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                supplierSelect.setModel(com);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    public void setRecordsToTable(){
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/el_coco_db","root","root");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM po_cart");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                
                int po_cart_id = rs.getInt("po_cart_id");
                int po_invoice_id = rs.getInt("po_invoice_id");
                String suppliername = rs.getString("suppliername");
                String product = rs.getString("product");
                double price = rs.getDouble("price");
                int quantity = rs.getInt("quantity");
                double total = rs.getDouble("total");
                String orderstatus = rs.getString("orderstatus");
                String deliverytype = rs.getString("deliverytype");
                String modeofpayment = rs.getString("modeofpayment");
                String paymentstatus = rs.getString("paymentstatus");
                String date = rs.getString("date");
                
                Object[] obj = {po_cart_id, po_invoice_id, suppliername, product, price, quantity, total, orderstatus, deliverytype, modeofpayment, paymentstatus, date };
                
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)purchasedOrderReportTable.getModel();
                model.addRow(obj);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchasedOrderReportTable = new javax.swing.JTable();
        fromDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        refreshBtn = new javax.swing.JButton();
        allSalesBtn2 = new javax.swing.JButton();
        supplierSelect = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        editBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editBtn.setBackground(new java.awt.Color(44, 119, 33));
        editBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        editBtn.setText("ALL PURCHASED ORDERS");
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setFocusable(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 310, 40));

        purchasedOrderReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PO Cart ID", "PO Invoice ID", "Supplier Name", "Product", "Price", "Quantity", "Total", "Order Status", "Delivery Type", "Payment Mode", "Payment Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchasedOrderReportTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(purchasedOrderReportTable);
        if (purchasedOrderReportTable.getColumnModel().getColumnCount() > 0) {
            purchasedOrderReportTable.getColumnModel().getColumn(0).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(1).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(2).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(3).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(4).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(5).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(6).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(7).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(8).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(9).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(10).setResizable(false);
            purchasedOrderReportTable.getColumnModel().getColumn(11).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1500, 400));

        fromDate.setBackground(new java.awt.Color(255, 255, 255));
        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel2.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 40));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel9.setText("Select Supplier");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 40));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel10.setText("To:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        toDate.setBackground(new java.awt.Color(255, 255, 255));
        toDate.setDateFormatString("yyyy-MM-dd");
        toDate.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel2.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 130, 40));

        refreshBtn.setBackground(new java.awt.Color(44, 119, 33));
        refreshBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh (1).png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setFocusable(false);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel2.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 70, 120, 40));

        allSalesBtn2.setBackground(new java.awt.Color(44, 119, 33));
        allSalesBtn2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        allSalesBtn2.setForeground(new java.awt.Color(255, 255, 255));
        allSalesBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (1).png"))); // NOI18N
        allSalesBtn2.setText("Search Between Dates");
        allSalesBtn2.setFocusable(false);
        allSalesBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSalesBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(allSalesBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 350, 40));

        supplierSelect.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        supplierSelect.setFocusable(false);
        supplierSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierSelectActionPerformed(evt);
            }
        });
        jPanel2.add(supplierSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel11.setText("From:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        editBtn1.setBackground(new java.awt.Color(44, 119, 33));
        editBtn1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        editBtn1.setForeground(new java.awt.Color(255, 255, 255));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        editBtn1.setText("PRINT");
        editBtn1.setBorder(null);
        editBtn1.setBorderPainted(false);
        editBtn1.setFocusable(false);
        editBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(editBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1560, 550));

        jPanel1.setBackground(new java.awt.Color(0, 224, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Purchased Order Invoices Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 670, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try{
            ReportView r = new ReportView("C:\\Users\\james\\Documents\\2y1 Activities\\OOP Projects\\ElCoco\\src\\reports\\PurchasedOrderInvoicesReport.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        purchasedOrderReportTable.setModel(new DefaultTableModel(null, new String[]{"Purchase Order ID", "PO Invoice ID", "Total Quantity", "Total Amount", "Date"}));
        setRecordsToTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void allSalesBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSalesBtn2ActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String from = sdf.format(fromDate.getDate());
        String to = sdf.format(toDate.getDate());

        if(from.equals(" ") || to.equals(" ")){
            JOptionPane.showMessageDialog(this, "Select Dates!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{

            try{
                String query = "SELECT * FROM po_cart WHERE date >= '"+from+"' AND date <= '"+to+"' ";
                PreparedStatement pst = DBConnector.mycon().prepareStatement(query);

                ResultSet rs = pst.executeQuery(query);

                purchasedOrderReportTable.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }

            try{

                DefaultTableModel model = (DefaultTableModel) purchasedOrderReportTable.getModel();
                JRTableModelDataSource ds = new JRTableModelDataSource(model);
                String r = "C:\\Users\\james\\Documents\\2y1 Activities\\OOP Projects\\ElCoco\\src\\reports\\BetweenDatesPurchasedOrder1Report.jrxml";

                JasperReport jr = JasperCompileManager.compileReport(r);

                //get dates
                System.out.println(from);
                System.out.println(to);

                //get sum of amount due
                double total = 0.0;
                for (int ix = 0; ix < purchasedOrderReportTable.getRowCount(); ix++){
                    double amount = Double.parseDouble(purchasedOrderReportTable.getValueAt(ix, 6).toString());
                    total += amount;
                }
                System.out.println(total);
                
                //total quantity
                int totalq = 0;
                for (int ix = 0; ix < purchasedOrderReportTable.getRowCount(); ix++){
                    double amount = Double.parseDouble(purchasedOrderReportTable.getValueAt(ix, 5).toString());
                    totalq += amount;
                }

                HashMap<String, Object> p = new HashMap<String, Object>();
                p.put("FROM_DATE", from);
                p.put("TO_DATE", to);
                p.put("TOTAL_AMOUNT", total);
                p.put("TOTAL_QUANTITY", totalq);

                JasperPrint jp = JasperFillManager.fillReport(jr, p, ds);

                JasperViewer.viewReport(jp, false);

            }catch(Exception e){
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_allSalesBtn2ActionPerformed

    private void supplierSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierSelectActionPerformed

        String supp = supplierSelect.getSelectedItem().toString();
        String searchQuery = "SELECT * FROM po_cart WHERE suppliername ='"+supp+"'";
        try {
            PreparedStatement pst = DBConnector.mycon().prepareStatement(searchQuery);
            ResultSet rs = pst.executeQuery();
            purchasedOrderReportTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_supplierSelectActionPerformed

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        try{
            
            DefaultTableModel model = (DefaultTableModel) purchasedOrderReportTable.getModel();
            JRTableModelDataSource ds = new JRTableModelDataSource(model);
            String r = "C:\\Users\\james\\Documents\\2y1 Activities\\OOP Projects\\ElCoco\\src\\reports\\SelectedSupplierName.jrxml";
            
            JasperReport jr = JasperCompileManager.compileReport(r);
            
            //get this month
            YearMonth thisMonth    = YearMonth.now();
            DateTimeFormatter monthYearFormatter = DateTimeFormatter.ofPattern("MMMM yyyy");
            String thisMonth1 = thisMonth.format(monthYearFormatter);
            
            //get sum of amount due
            double total = 0.0;
            for (int ix = 0; ix < purchasedOrderReportTable.getRowCount(); ix++){
                double amount = Double.parseDouble(purchasedOrderReportTable.getValueAt(ix, 6).toString());
                total += amount;
            }
            System.out.println(total);
            
            //total quantity
                int totalq = 0;
                for (int ix = 0; ix < purchasedOrderReportTable.getRowCount(); ix++){
                    double amount = Double.parseDouble(purchasedOrderReportTable.getValueAt(ix, 5).toString());
                    totalq += amount;
                }
            
            String suppname = supplierSelect.getSelectedItem().toString();
            
            HashMap<String, Object> p = new HashMap<String, Object>();
            p.put("SUPPLIER_NAME", suppname);
            p.put("TOTAL_AMOUNT", total);
            p.put("TOTAL_QUANTITY", totalq);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, p, ds);
            
            JasperViewer.viewReport(jp, false);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_editBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuchasedOrderReport_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuchasedOrderReport_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuchasedOrderReport_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuchasedOrderReport_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuchasedOrderReport_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allSalesBtn2;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable purchasedOrderReportTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JComboBox<String> supplierSelect;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
