/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package salesAndInventorySystem;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author james
 */
public class PurchasedOrderTransactions extends javax.swing.JFrame {

    /** Creates new form PurchasedOrderTransactions */
    public PurchasedOrderTransactions() {
        initComponents();
        setRecordsToTable();
        showIcon();
    }
    
    private void showIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("wine__.png")));
    }
    
    public void setRecordsToTable(){
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/el_coco_db","root","root");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM purchased_order");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                
                int purchased_order_id = rs.getInt("purchased_order_id");
                int po_invoice_id = rs.getInt("po_invoice_id");
                int totalquantity = rs.getInt("totalquantity");
                int totalamount = rs.getInt("totalamount");
                String date = rs.getString("date");
                
                Object[] obj = {purchased_order_id, po_invoice_id, totalquantity, totalamount, date };
                
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)purchasedOrderTransactionsTb.getModel();
                model.addRow(obj);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();
        printBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchasedOrderTransactionsTb = new javax.swing.JTable();
        fromDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        allSalesBtn2 = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 224, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Purchased Order Transactions");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 630, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 145)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel8.setText("Search ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 60, 40));

        searchTf.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        searchTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTfActionPerformed(evt);
            }
        });
        searchTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTfKeyReleased(evt);
            }
        });
        jPanel2.add(searchTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 180, 40));

        printBtn.setBackground(new java.awt.Color(44, 119, 33));
        printBtn.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        printBtn.setText("PRINT");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        jPanel2.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 140, 40));

        purchasedOrderTransactionsTb.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        purchasedOrderTransactionsTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchased Order ID", "PO Invoice ID", "Total Quantity", "Total Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchasedOrderTransactionsTb.getTableHeader().setReorderingAllowed(false);
        purchasedOrderTransactionsTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasedOrderTransactionsTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchasedOrderTransactionsTb);
        if (purchasedOrderTransactionsTb.getColumnModel().getColumnCount() > 0) {
            purchasedOrderTransactionsTb.getColumnModel().getColumn(0).setResizable(false);
            purchasedOrderTransactionsTb.getColumnModel().getColumn(1).setResizable(false);
            purchasedOrderTransactionsTb.getColumnModel().getColumn(2).setResizable(false);
            purchasedOrderTransactionsTb.getColumnModel().getColumn(3).setResizable(false);
            purchasedOrderTransactionsTb.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 950, 360));

        fromDate.setBackground(new java.awt.Color(255, 255, 255));
        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel2.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 40));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel9.setText("From:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel10.setText("To:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 20));

        toDate.setBackground(new java.awt.Color(255, 255, 255));
        toDate.setDateFormatString("yyyy-MM-dd");
        toDate.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel2.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 40));

        allSalesBtn2.setBackground(new java.awt.Color(44, 119, 33));
        allSalesBtn2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        allSalesBtn2.setForeground(new java.awt.Color(255, 255, 255));
        allSalesBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (1).png"))); // NOI18N
        allSalesBtn2.setText("Search Between Dates");
        allSalesBtn2.setFocusable(false);
        allSalesBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSalesBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(allSalesBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 260, 40));

        refreshBtn.setBackground(new java.awt.Color(44, 119, 33));
        refreshBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh (1).png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setFocusable(false);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel2.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTfActionPerformed

    private void searchTfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTfKeyReleased
        DefaultTableModel table = (DefaultTableModel)purchasedOrderTransactionsTb.getModel();
        String search = searchTf.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        purchasedOrderTransactionsTb.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchTfKeyReleased

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        try{
            ReportView r = new ReportView("C:\\Users\\james\\Documents\\2y1 Activities\\OOP Projects\\ElCoco\\src\\reports\\PurchasedOrderReport.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);
        }catch(Exception e){

        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void purchasedOrderTransactionsTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasedOrderTransactionsTbMouseClicked

    }//GEN-LAST:event_purchasedOrderTransactionsTbMouseClicked

    private void allSalesBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSalesBtn2ActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String from = sdf.format(fromDate.getDate());
        String to = sdf.format(toDate.getDate());

        if(from.equals(" ") || to.equals(" ")){
            JOptionPane.showMessageDialog(this, "Select Dates!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{

            try{
                String query = "SELECT * FROM purchased_order WHERE date >= '"+from+"' AND date <= '"+to+"' ";
                PreparedStatement pst = DBConnector.mycon().prepareStatement(query);

                ResultSet rs = pst.executeQuery(query);

                purchasedOrderTransactionsTb.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }

            try{

                DefaultTableModel model = (DefaultTableModel) purchasedOrderTransactionsTb.getModel();
                JRTableModelDataSource ds = new JRTableModelDataSource(model);
                String r = "C:\\Users\\james\\Documents\\2y1 Activities\\OOP Projects\\ElCoco\\src\\reports\\BetweenDatesPurchasedOrderReport.jrxml";

                JasperReport jr = JasperCompileManager.compileReport(r);

                //get dates

                System.out.println(from);
                System.out.println(to);

                //get sum of amount due
                double total = 0.0;
                for (int ix = 0; ix < purchasedOrderTransactionsTb.getRowCount(); ix++){
                    double amount = Double.parseDouble(purchasedOrderTransactionsTb.getValueAt(ix, 3).toString());
                    total += amount;
                }
                System.out.println(total);
                //total quantity
                int totalq = 0;
                for (int ix = 0; ix < purchasedOrderTransactionsTb.getRowCount(); ix++){
                    double amount = Double.parseDouble(purchasedOrderTransactionsTb.getValueAt(ix, 2).toString());
                    totalq += amount;
                }

                HashMap<String, Object> p = new HashMap<String, Object>();
                p.put("FROM_DATE", from);
                p.put("TO_DATE", to);
                p.put("TOTAL_AMOUNT", total);
                p.put("TOTAL_QUANTITY", totalq);

                JasperPrint jp = JasperFillManager.fillReport(jr, p, ds);

                JasperViewer.viewReport(jp, false);

            }catch(Exception e){
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_allSalesBtn2ActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        purchasedOrderTransactionsTb.setModel(new DefaultTableModel(null, new String[]{"Purchase Order ID", "PO Invoice ID", "Total Quantity", "Total Amount", "Date"}));
        setRecordsToTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchasedOrderTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchasedOrderTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchasedOrderTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchasedOrderTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchasedOrderTransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allSalesBtn2;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    public javax.swing.JTable purchasedOrderTransactionsTb;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField searchTf;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables

}
